name: LobbySystem
main: LobbySystem\MainClass
src-namespace-prefix: LobbySystem

version: 1.0.0-beta
api: [ 4.0.0, 5.0.0 ]

description: A higly customizable LobbySystem for everyone! (easy to use)
author: EdoLegendsPM